### ISSUE TITLE
打开pdm文件报NullPointerException

### ISSUE THREAD

**Issue by cloudecho** [yjgoo/pdm-viewer#1]
用window下的powerdesigner15.1可以打开。但用PDMViewer报错如下：
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at org.yjgoo.jpdmviewer.pdm.PDMFileModel.parse(PDMFileModel.java:34)
    at org.yjgoo.jpdmviewer.pdm.PDMFileModel.loadFile(PDMFileModel.java:25)
    at org.yjgoo.jpdmviewer.ui.MainWindow.loadPDM(MainWindow.java:77)
    at org.yjgoo.jpdmviewer.ui.menu.MainMenu.openFileHandler(MainMenu.java:58)
    at org.yjgoo.jpdmviewer.ui.menu.MainMenu.access$0(MainMenu.java:34)
    at org.yjgoo.jpdmviewer.ui.menu.MainMenu$1.actionPerformed(MainMenu.java:29)
    at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
    at java.awt.MenuItem.processEvent(MenuItem.java:628)
    at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
    at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:738)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

猜想PDMViewer不支持高版本的pdm（例如15），这个项目还会继续下去吗？
期待回复

**Comment by viquu** [comment]
我在MAC下打开比较亲的PDM好像没有遇到问题
